<h3 class="sub-header">سخن روز</h3>
<div class="col-lg-12 col-md-12 text-center">
<?php
### GENERATED BY POOYA SABRAMOOZ ###

	$quotations_row = QUOTATIONS::quotations_SelectOneRandom();

?>
<blockquote class="blockquote-reverse">
  <p><?php echo $quotations_row['text']; ?></p>
  <footer style="direction:rtl;color:#3399CC"><?php echo $quotations_row['author']; ?></footer>
</blockquote>
<hr>
<img src="images/Norooz.jpg" class="img-rounded" height="400">
</div>
